In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
f = open('../Data/allClean.json')
data = json.load(f)
matches = data['all_data']
print(len(matches))

10000

In [4]:
def get_champions_name(_id):
    """
    this functions takes an _id and returns the associate champions name
    :param _id: any integer from 1 to 555. if there is a champion, it will return the name.
    :return: champions name
    """
    all_champion_id = {
        1: "Annie",
        2: "Olaf",
        3: "Galio",
        4: "TwistedFate",
        5: "XinZhao",
        6: "Urgot",
        7: "LeBlanc",
        8: "Vladimir",
        9: "Fiddlesticks",
        10: "Kayle",
        11: "Master Yi",
        12: "Alistar",
        13: "Ryze",
        14: "Sion",
        15: "Sivir",
        16: "Soraka",
        17: "Teemo",
        18: "Tristana",
        19: "Warwick",
        20: "Nunu",
        21: "MissFortune",
        22: "Ashe",
        23: "Tryndamere",
        24: "Jax",
        25: "Morgana",
        26: "Zilean",
        27: "Singed",
        28: "Evelynn",
        29: "Twitch",
        30: "Karthus",
        31: "Cho'Gath",
        32: "Amumu",
        33: "Rammus",
        34: "Anivia",
        35: "Shaco",
        36: "Dr.Mundo",
        37: "Sona",
        38: "Kassadin",
        39: "Irelia",
        40: "Janna",
        41: "Gangplank",
        42: "Corki",
        43: "Karma",
        44: "Taric",
        45: "Veigar",
        48: "Trundle",
        50: "Swain",
        51: "Caitlyn",
        53: "Blitzcrank",
        54: "Malphite",
        55: "Katarina",
        56: "Nocturne",
        57: "Maokai",
        58: "Renekton",
        59: "JarvanIV",
        60: "Elise",
        61: "Orianna",
        62: "Wukong",
        63: "Brand",
        64: "LeeSin",
        67: "Vayne",
        68: "Rumble",
        69: "Cassiopeia",
        72: "Skarner",
        74: "Heimerdinger",
        75: "Nasus",
        76: "Nidalee",
        77: "Udyr",
        78: "Poppy",
        79: "Gragas",
        80: "Pantheon",
        81: "Ezreal",
        82: "Mordekaiser",
        83: "Yorick",
        84: "Akali",
        85: "Kennen",
        86: "Garen",
        89: "Leona",
        90: "Malzahar",
        91: "Talon",
        92: "Riven",
        96: "Kog'Maw",
        98: "Shen",
        99: "Lux",
        101: "Xerath",
        102: "Shyvana",
        103: "Ahri",
        104: "Graves",
        105: "Fizz",
        106: "Volibear",
        107: "Rengar",
        110: "Varus",
        111: "Nautilus",
        112: "Viktor",
        113: "Sejuani",
        114: "Fiora",
        115: "Ziggs",
        117: "Lulu",
        119: "Draven",
        120: "Hecarim",
        121: "Kha'Zix",
        122: "Darius",
        126: "Jayce",
        127: "Lissandra",
        131: "Diana",
        133: "Quinn",
        134: "Syndra",
        136: "AurelionSol",
        141: "Kayn",
        142: "Zoe",
        143: "Zyra",
        145: "Kai'sa",
        150: "Gnar",
        154: "Zac",
        157: "Yasuo",
        161: "Vel'Koz",
        163: "Taliyah",
        164: "Camille",
        201: "Braum",
        202: "Jhin",
        203: "Kindred",
        222: "Jinx",
        223: "TahmKench",
        235: "Senna",
        236: "Lucian",
        238: "Zed",
        240: "Kled",
        245: "Ekko",
        246: "Qiyana",
        254: "Vi",
        266: "Aatrox",
        267: "Nami",
        268: "Azir",
        350: "Yuumi",
        412: "Thresh",
        420: "Illaoi",
        421: "Rek'Sai",
        427: "Ivern",
        429: "Kalista",
        432: "Bard",
        497: "Rakan",
        498: "Xayah",
        516: "Ornn",
        517: "Sylas",
        523: "Aphelios",
        518: "Neeko",
        555: "Pyke",
        777: "Yone",
        875: "Sett",
        876: "Lillia",


    }
    return all_champion_id.get(_id)

In [5]:
champArray = []

for match in matches:
    
    #get the 10 champions, in order by participants
    #store these 10 in an array
    for participant in match['participants']:
        identity = participant['championId']
        
        #convert to champ name?
        name = get_champions_name(identity)
        #add name to array
        champArray.append( name )

    champArray.append( int(match['team1Win']) )
    

champNames = np.asarray(champArray)
champNames = champNames.reshape( (-1,11))
print(champNames)

[['Jhin' 'Lulu' 'Mordekaiser' ... 'Ekko' 'Jax' '1']
 ['Swain' 'Ashe' 'Kayn' ... 'Aphelios' 'Lux' '0']
 ['Ashe' 'Veigar' 'Thresh' ... 'LeBlanc' 'Yorick' '0']
 ...
 ['Tristana' 'Lux' 'XinZhao' ... 'Annie' 'Senna' '0']
 ['Wukong' 'Thresh' 'Ashe' ... 'Zed' 'Leona' '0']
 ['Riven' 'Jax' 'Poppy' ... 'Yasuo' 'Yone' '0']]

In [6]:
#convert array to dataframe
cat = []
for i in range(1,11):
    cat.append('player{}'.format(i))
cat.append('team1Win')
dataframe = pd.DataFrame(data=champNames, columns = cat)
dataframe.head()

,player1,player2,player3,player4,player5,player6,player7,player8,player9,player10,team1Win
0,Jhin,Lulu,Mordekaiser,Graves,Kassadin,Kai'sa,Janna,Karma,Ekko,Jax,1
1,Swain,Ashe,Kayn,Yasuo,Camille,Pantheon,Galio,Vladimir,Aphelios,Lux,0
2,Ashe,Veigar,Thresh,Gnar,LeeSin,Kha'Zix,Jhin,Morgana,LeBlanc,Yorick,0
3,Tristana,Akali,Yone,Swain,Volibear,Sett,Nidalee,Fiora,Ekko,Vayne,1
4,Jax,Diana,Mordekaiser,Lulu,Lucian,Lux,Kennen,Ezreal,Kha'Zix,Yasuo,1

In [7]:
dataframe.to_csv('../Data/champsOG.csv', index=False)